---

- name: user and group handling
  when:
    - not running_in_check_mode
    - chartmuseum_system_user != "root"
  block:
    - name: create chartmuseum group
      ansible.builtin.group:
        name: "{{ chartmuseum_system_group }}"
        state: present
        system: true

    - name: create chartmuseum user
      ansible.builtin.user:
        name: "{{ chartmuseum_system_user }}"
        groups: "{{ chartmuseum_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent

- name: create install directory
  when:
    - not running_in_check_mode
  ansible.builtin.file:
    path: "{{ chartmuseum_install_path }}"
    state: directory
    owner: "{{ chartmuseum_system_user }}"
    group: "{{ chartmuseum_system_group }}"
    mode: "0755"

- name: deploy and activate chartmuseum version {{ chartmuseum_version }}
  when:
    - not running_in_check_mode
  bodsch.core.deploy_and_activate:
    src_dir: "{{ chartmuseum_local_tmp_directory }}"
    install_dir: "{{ chartmuseum_install_path }}"
    link_dir: "/usr/bin"
    remote_src: "{{ ('true' if chartmuseum_direct_download else 'false') | bool }}"
    owner: "{{ chartmuseum_system_user }}"
    group: "{{ chartmuseum_system_group }}"
    mode: "0755"
    items:
      - name: "{{ chartmuseum_release.binary }}"
        capability: "cap_net_raw+ep"
  notify:
    - restart chartmuseum

- name: create local storage directory
  when:
    - not running_in_check_mode
    - chartmuseum_service is defined
    - chartmuseum_service.storage is defined
    - chartmuseum_service.storage.backend is defined
    - chartmuseum_service.storage.backend == "local"
    - chartmuseum_service.storage.local is defined
    - chartmuseum_service.storage.local.rootdir is defined
    - chartmuseum_service.storage.local.rootdir | string | length > 0
  ansible.builtin.file:
    path: "{{ chartmuseum_service.storage.local.rootdir }}"
    state: directory
    owner: "{{ chartmuseum_system_user }}"
    group: "{{ chartmuseum_system_group }}"
    mode: "0755"

- name: systemd
  when:
    - not running_in_check_mode
    - ansible_facts.service_mgr | lower == "systemd"
  block:
    - name: create chartmuseum run configuration
      ansible.builtin.template:
        src: "default/chartmuseum.j2"
        dest: "{{ chartmuseum_defaults_directory }}/chartmuseum"
        force: true
        owner: root
        group: "{{ chartmuseum_system_group }}"
        mode: "0640"
      notify:
        - restart chartmuseum

    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/chartmuseum.service.j2"
        dest: "{{ systemd_lib_directory }}/chartmuseum.service"
        owner: root
        group: root
        mode: "0644"
      notify:
        - daemon-reload
        - restart chartmuseum

- name: openrc
  when:
    - not running_in_check_mode
    - ansible_facts.service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/chartmuseum.j2"
        dest: "/etc/conf.d/chartmuseum"
        owner: root
        group: root
        mode: "0644"

    - name: create openrc init configuration
      ansible.builtin.template:
        src: "init/openrc/init.d/chartmuseum.j2"
        dest: "/etc/init.d/chartmuseum"
        owner: root
        group: root
        mode: "0750"

- name: create custom fact file
  when:
    - not running_in_check_mode
  bodsch.core.facts:
    name: chartmuseum
    facts:
      version: "{{ chartmuseum_version }}"
